### ISSUE TITLE
Provide where a class is referenced from

### ISSUE THREAD

**Issue by matiassingers** [symdiff/symdiff#1]
I realize this is impossible when you are currently passing around the raw content of the files, and not the file paths.

But I believe being able to say ".my-unused-class was used in template-foo.html" would be really beneficial.

**Comment by prayerslayer** [comment]
I agree that this would be useful information, but I believe this is best handled by the plugins for various build tools as they already deal with files. They should keep track of which class was used in which file (might be more than one) and group the reporting accordingly. I will create an issue in `gulp-symdiff` and `grunt-symdiff`.
